import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react';

function Features({icon,description,title}){

  return(
    <div className="single-feature wow fadeInUp" data-wow-delay=".4s">
      <i className={icon}></i>
      <h3>{title}</h3>
      <p>{description}</p>
    </div>
  )
}

function Header(){
  const [novo,setNovo] = useState();

  return(
    <header className="header navbar-area">
        <div className="container">
          <div className="row align-items-center">
            <div className="col-lg-12">
              <div className="nav-inner">
                <nav className="navbar navbar-expand-lg">
                  <a className="navbar-brand" href="index.html">
                    <Image src="/assets/images/logo/white-logo.png" alt="Logo" width={130} height={40} />
                  </a>
                  <button onClick={() => setNovo(true)} className="navbar-toggler mobile-menu-btn" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span className="toggler-icon"></span>
                    <span className="toggler-icon"></span>
                    <span className="toggler-icon"></span>
                  </button>
                  <div className={"collapse navbar-collapse sub-menu-bar "+(novo ? "show" : "")} id="navbarSupportedContent">
                    <ul className="navbar-nav ms-auto">
                      <li className="nav-item">
                        <a href="#home" className="page-scroll active" aria-label="Toggle navigation">Início</a>
                      </li>
                      <li className="nav-item">
                        <a href="#features" className="page-scroll" aria-label="Toggle navigation">Funcionalidades</a>
                      </li>
                      <li className="nav-item">
                        <a href="#clients" className="page-scroll" aria-label="Toggle navigation">Clientes</a>
                      </li>
                      <li className="nav-item">
                        <a rel="noreferrer" target="_blank" href="https://api.whatsapp.com/send?phone=5521990452839&text=Ol%C3%A1%2C%20entrei%20pelo%20site%2C%20gostaria%20de%20informa%C3%A7%C3%B5es%20sobre%20o%20aplicativo." aria-label="Toggle navigation">Contato</a>
                      </li>
                    </ul>
                  </div> 
                  <div className="button add-list-button">
                    <a href="https://usemed.app" className="btn">Entrar</a>
                  </div>                          
                </nav>
              </div>
            </div>
          </div> 
        </div> 
      </header>
  )
}



export default function Home() {
  return (
    <div >
      <Head>
        <title>Usemed - Tornar o mundo um lugar melhor através da tecnologia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header />
      
      <section id="home" className="hero-area">
        <div className="container">
          <div className="row align-items-center">
            <div className="col-lg-5 col-md-12 col-12">
              <div className="hero-content">
                <h1 className="wow fadeInLeft" data-wow-delay=".4s">Um aplicativo poderoso para sua clínica.</h1>
                <p className="wow fadeInLeft" data-wow-delay=".6s">
                  Tenha acesso a todas as informações dos seus pacientes em todas as plataformas, <b>IOS, Android e Web</b>. Baixe agora o aplicativo.
                </p>
                <div className="button wow fadeInLeft" data-wow-delay=".8s">
                  <a href="#" className="btn"><i className="lni lni-apple"></i> App Store</a>
                  <a rel="noreferrer" target="_blank" href="https://play.google.com/store/apps/details?id=br.com.usemed" className="btn btn-alt"><i className="lni lni-play-store"></i> Google Play</a>
                </div>
              </div>
            </div>
            <div className="col-lg-7 col-md-12 col-12">
              <div className="hero-image wow fadeInRight" data-wow-delay=".4s">
                <Image src="/assets/images/hero/phone.png" alt="Logo" width={700} height={550} />
              </div>
            </div>
          </div>
        </div>
      </section>
      <section id="features" className="features section">
        <div className="container">
          <div className="row">
            <div className="col-12">
              <div className="section-title">
                <h3 className="wow zoomIn" data-wow-delay=".2s">Funcionalidades</h3>
                <h2 className="wow fadeInUp" data-wow-delay=".4s">Sua experiência fica cada vez melhor com o tempo.</h2>
              </div>
            </div>
          </div>
          <div className="row">
          <div className="col-lg-4 col-md-6 col-12">
              <Features icon="lni lni-alarm" title="Avisos de pendências" description="Receber lembretes das pendências dos atendimentos é fundamental para manter os prontuários atualizados e organizados."  />
            </div>
            <div className="col-lg-4 col-md-6 col-12">
              <Features icon="lni lni-calendar" title="Agenda" description="Tenha o controle da agenda da sua equipe  de forma prática e em tempo real através do agendamento online. Na agenda é possível finalizar, remarcar e desmarcar atendimentos e ter acesso atualizado ao status de cada atendimento. As informações da agenda podem ser acessadas de forma diária, semanal ou mensal."  />
            </div>
            <div className="col-lg-4 col-md-6 col-12">
              <Features icon="lni lni-book" title="Ficha de atendimento" description="Espaço destinado ao cadastro dos atendimentos de forma prática e rápida,  informando profissional responsável, local, tipo de procedimento, especialidade do tratamento e data/horário reservado para o atendimento."  />
            </div>
            <div className="col-lg-4 col-md-6 col-12">
              <Features icon="lni lni-first-aid" title="Prontuário eletronico" description="É através do prontuário eletrônico que a equipe consegue acessar todas as informações cadastradas do paciente, de forma prática e fácil, quando quiser e onde estiver. O prontuário permite o acesso a outros campos como informações cadastrais, ficha de avaliação, ficha de evolução, plano terapêutico, orientações parentais, discussão de caso, anexo de arquivos, instrumento de avaliação e foto do paciente."  />
            </div>
            <div className="col-lg-4 col-md-6 col-12">
              <Features icon="lni lni-book" title="Ficha de avaliação" description="A avaliação é um dos momentos mais importantes na prestação do serviço de saúde, pensando nisso, é fundamental armazenamento de informações de forma segura e permanente, fácil acesso por profissionais e gestores e um processo de avaliação padronizado e personalizado para as necessidades da clínica e demanda de cada profissional."  />
            </div>
            <div className="col-lg-4 col-md-6 col-12">
              <Features icon="lni lni-fireworks" title="Ficha de evolução" description="Na ficha de evolução é registrado como o paciente estava antes, durante e ao final do atendimento, as condutas estabelecidas e como o paciente tem respondido ao tratamento. É importante que a clínica mantenha a ficha de evolução de seus pacientes devidamente atualizadas e que esses registros sejam armazenados de forma segura."  />
            </div>
            <div className="col-lg-4 col-md-6 col-12">
              <Features icon="lni lni-bubble" title="Discussão de caso" description="Espaço para discussão de casos de pacientes pela equipe que os acompanham. As informações registradas ficam armazenadas permanente e podem ser acessadas posteriormente."  />
            </div>
            <div className="col-lg-4 col-md-6 col-12">
              <Features icon="lni lni-postcard" title="Orientações parentais" description="Para potencializar a evolução do paciente, é importante a continuidade do tratamento no dia a dia. Para isso é importante que a família tenha acesso as orientações parentais. Neste espaço o profissional terá liberdade de deixar registrado essas orientações que são passadas para a família, promovendo assistência às famílias e garantindo o respaldo sobre o que é orientado."  />
            </div>
            <div className="col-lg-4 col-md-6 col-12">
              <Features icon="lni lni-thought" title="Plano terapêutico" description="É no plano terapêutico que as terapeutas informam os objetivos estabelecidos para o paciente. O plano terapêutico pode ser acessado pela família do paciente e atualizado sempre que necessário pelas terapeutas responsáveis pelo caso."  />
            </div>
          </div>
        </div>
      </section>
      <section className="our-achievement section">
        <div className="container">
          <div className="row">
            <div className="col-lg-10 offset-lg-1 col-md-12 col-12">
              <div className="title">
                <h2>Nossos números</h2>
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col-lg-8 offset-lg-2 col-md-12 col-12">
              <div className="row">
                <div className="col-lg-3 col-md-3 col-12">
                  <div className="single-achievement wow fadeInUp" data-wow-delay=".2s">
                    <h3 className="counter"><span id="secondo1" className="countup" cup-end="254">254</span></h3>
                    <p>Atendimentos</p>
                  </div>
                </div>
                <div className="col-lg-3 col-md-3 col-12">
                  <div className="single-achievement wow fadeInUp" data-wow-delay=".2s">
                    <h3 className="counter"><span id="secondo1" className="countup" cup-end="84">84</span></h3>
                    <p>Pacientes</p>
                  </div>
                </div>
                <div className="col-lg-3 col-md-3 col-12">
                  <div className="single-achievement wow fadeInUp" data-wow-delay=".4s">
                    <h3 className="counter"><span id="secondo2" className="countup" cup-end="30">30</span></h3>
                    <p>Profissionais</p>
                  </div>
                </div>
                <div className="col-lg-3 col-md-3 col-12">
                  <div className="single-achievement wow fadeInUp" data-wow-delay=".6s">
                    <h3 className="counter"><span id="secondo3" className="countup" cup-end="2">2</span></h3>
                    <p>Clíentes</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section id="clients" className="features section" >
        <div className="container">
          <div className="row">
            <div className="col-lg-3 col-md-3 col-12" style={{textAlign:"center"}}>
              <Image src="/assets/images/clients/talitaaraujo.png" alt="Logo" width="230" height="100" />
            </div>
            
          </div>
        </div>
      </section>
      <footer className="footer">
       
        <div className="footer-top">
          <div className="container">
            <div className="row">
            <div className="col-lg-4 col-md-4 col-12">
              <div className="single-footer f-about">
                <div className="logo">
                  <Image src="/assets/images/logo/white-logo.png" alt="Logo" width={130} height={40} />
                </div>
                <p>Tornar o mundo um lugar melhor através da tecnologia.</p>
                <ul className="social">
                  <li><a rel="noreferrer" target="_blank" href="https://www.facebook.com/usemedapp"><i className="lni lni-facebook-filled"></i></a></li>                               
                  <li><a rel="noreferrer" target="_blank" href="https://www.instagram.com/usemed.app"><i className="lni lni-instagram"></i></a></li>
                  <li><a rel="noreferrer" target="_blank" href="https://www.linkedin.com/company/usemed"><i className="lni lni-linkedin-original"></i></a></li>
                </ul>
              </div>
            </div>
            <div className="col-lg-8 col-md-8 col-12">
              <div className="row">
                <div className="col-lg-3 col-md-6 col-12">
                  <div className="single-footer f-link">
                    <h3>Legal</h3>
                    <ul>
                      <li><Link href="/privacy">Política de Privacidade</Link></li>
                    </ul>
                  </div>              
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
    </div>
  )
}
